---
title: "EDS232_lab1"
author: "Joe DeCesaro"
date: "1/3/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load packages, installing if missing
if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}
librarian::shelf(
  dismo, dplyr, DT, ggplot2, here, htmltools, leaflet, mapview, purrr, raster, readr, rgbif, rgdal, rJava, sdmpredictors, sf, spocc, tidyr, geojsonio)
select <- dplyr::select # overwrite raster::select

# set random seed for reproducibility
set.seed(42)

# directory to store data
dir_data <- here("data/sdm")
dir.create(dir_data, showWarnings = F)
```

## Get Species Observations
```{r}
obs_csv <- file.path(dir_data, "obs.csv")
obs_geo <- file.path(dir_data, "obs.geojson")

# get species occurrence data from GBIF with coordinates
(res <- spocc::occ(
  query = 'Enhydra lutris', 
  from = 'gbif', has_coords = T,
  limit = 10000))
```

### Extract data from the result
```{r}
df <- res$gbif$data[[1]] 
nrow(df)
```

### convert to points of observation from lon/lat columns in data frame
```{r}
obs <- df %>% 
  sf::st_as_sf(
    coords = c("longitude", "latitude"),
    crs = st_crs(4326))

readr::write_csv(df, obs_csv)
#sf::write_sf(obs, obs_geo)
geojsonio::geojson_write(obs, obs_geo)
# show points on map
mapview::mapview(obs, map.types = "Esri.OceanBasemap")
```

## Question 1: How many observations total are in GBIF for your species?
13,716

## Question 2: Do you see any odd observations, like marine species on land or vice versa?

